In [10]:
import pynapple as nap
from pathlib import Path

#subject definitions for tumor cohort
nwb_paths = [
    Path("/data_store2/neuropixels/nwb/old/NP93_B1/NP93_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP95_B1/NP95_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP101_B3/NP101_B3.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP105_B1/NP105_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP113_B1/NP113_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP114_B1/NP114_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP116_B2/NP116_B2.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP122_B1/NP122_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP128_B1/NP128_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP129_B1/NP129_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP132_B2/NP132_B2.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP132_B3/NP132_B3.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP136_B1/NP136_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP137_B1/NP137_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP138_B1/NP138_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP139_B1/NP139_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP139_B2/NP139_B2.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP147_B2/NP147_B2.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP150_B1/NP150_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP153_B1/NP153_B1.nwb"),
    Path("/data_store2/neuropixels/nwb/old/NP171_B1/NP171_B1.nwb"), # new gbm flair-
    Path("/data_store2/neuropixels/nwb/old/NP174_B3/NP174_B3.nwb"), # new gbm flair-
]   

### adjust for the depth of the probe
subj_list = [1, 2, 3, 5, 6, 6, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 16, 17, 17, 18, 19, 20, 20, 21, 22, 23]
path_list = ['ast', 'ast', 'gbm','oli', 'gbm', 'gbm', 'gbm', 'gbm', 'gbm', 'ast', 'ast', 'ast', 'ast', 'oli', 'oli', 'gbm', 'ast', 'ast', 'ast', 'ast', 'ast', 'ast', 'gbm', 'ast', 'ast', 'oli', 'gbm', 'gbm']
grade_list = [4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 3, 4, 4]
yield_list = [1, 57, 17, 1, 139, 178, 202, 49, 4, 30, 9, 29, 3, 77, 126, 30, 35, 10, 1, 34, 8, 42, 30, 10, 11, 22, 17, 24]
opercular_list = [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
region_list = ['aSTG','SFG','aSTG','SFG','vPrCG','vPrCG','vPrCG','pSTG','aMTG','MFG','aSTG','parsOp','MFG','PoCG','PoCG','pSTG','parsOr','vPrCG','pSTG','parsTr','pSTG','parsTr','SMG','parsTr','pSTG','vPrCG', 'aSTG', 'vPrCG']
age_list = [28, 28, 54, 34, 52, 52, 52, 59, 64, 34, 34, 34, 39, 43, 43, 63, 38, 43, 43, 29, 29, 29, 47, 31, 31, 41, 79, 55]
gender_list = [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0]

manual_exclude_lists = [
    [2], # NP93_B1.imec0
    [], # NP95_B1.imec0
    [29, 45, 55], # NP101_B3.imec0
    [130, 150, 151, 245, 371, 375, 377, 380, 386, 452], # NP105_B1.imec0
    [149, 156, 172, 173, 176, 217, 221, 253, 272, 276, 336, 487], # NP113_B1.imec0
    [22, 112, 149, 155, 161, 167, 176, 188, 190, 196, 213, 216, 241, 252, 255, 258, 286, 289, 307, 325, 326, 370, 395, 442, 443, 448, 449, 451, 455, 510, 549, 582, 692, 710, 717, 719, 722, 726, 729], # NP113_B1.imec1
    [385, 448], # NP113_B2.imec2
    [32, 34, 37, 39, 67, 142, 145, 175, 188, 310, 325, 331, 391, 392], # NP114_B1.imec0
    [11, 15, 30, 36], # NP116_B2.imec0
    [340, 382], # NP122_B1.imec0
    [54, 109, 152], # NP128_B1.imec0
    [], # NP128_B1.imec1
    [0, 6, 13, 33, 51, 52], # NP129_B1.imec0
    [19, 62, 111, 151, 171, 192, 199, 200, 205, 210, 227, 229, 244, 290, 298, 311], # NP132_B2.imec0
    [0, 10, 11, 15, 29, 45, 61, 112, 127, 149, 151, 158, 159, 172, 197, 209, 212, 218, 297, 315], # NP132_B3.imec0
    [334, 335, 333], # NP136_B1.imec0
    [361], # NP137_B1.imec0
    [], # NP138_B1.imec0
    [169, 195, 198], # NP138_B1.imec1
    [137, 149, 196, 197, 199, 206, 212, 220, 223, 231], # NP139_B1.imec0
    [129, 248, 249], # NP139_B1.imec1
    [28, 59, 60, 62, 63, 82, 104, 112, 146], # NP139_B2.imec0
    [47, 57, 59, 73, 82, 88, 116, 124, 125, 126, 127, 129, 148, 175, 194, 196, 239, 240, 242, 243, 244, 246, 253, 267, 245, 247, 248, 249, 250, 251, 254], # NP147_B2.imec0
    [], # NP150_B1.imec0
    [34, 64, 119, 135], # NP150_B1.imec1
    [20, 22, 47, 71, 80, 118, 125, 134, 141, 145, 146, 166, 173, 176, 191, 270, 298, 307, 385, 414, 391, 472, 473, 490, 491], # NP153_B1.imec0
    [16, 67, 74, 78, 91, 99, 221, 224, 225, 288], # NP171_B1.imec0
    [9, 11, 13, 23, 40, 43, 47, 59, 67, 72, 87, 104, 109, 122, 166, 169, 172, 175, 197, 199, 203, 205, 211, 212, 219, 227, 229, 230, 235, 237, 240, 251, 256, 295, 296], # NP174_B3.imec0
]

tipDepth_list = [
    5000, # NP93_B1.imec0
    6600, # NP95_B1.imec0
    5843, # NP101_B3.imec0
    7200, # NP105_B1.imec0
    7600, # NP113_B1.imec0
    7600, # NP113_B1.imec1
    7600, # NP113_B1.imec2
    6900, # NP114_B1.imec0
    6100, # NP116_B2.imec0
    6880, # NP122_B1.imec0
    6200, # NP128_B1.imec0
    6200, # NP128_B1.imec1
    6600, # NP129_B1.imec0
    3820, # NP132_B2.imec0
    3820, # NP132_B3.imec0
    6620, # NP136_B1.imec0
    7000, # NP137_B1.imec0
    7100, # NP138_B1.imec0
    7400, # NP138_B1.imec1
    6900, # NP139_B1.imec0
    7400, # NP139_B1.imec1
    7000, # NP139_B2.imec0
    6400, # NP147_B2.imec0
    6840, # NP150_B1.imec0
    6500, # NP150_B1.imec1
    6500, # NP153_B1.imec0
    6800, # NP171_B1.imec0
    5640, # NP174_B3.imec0
]

print(f"Loaded {len(nwb_paths)} NWB files")
print(len(subj_list))
print(len(grade_list))
print(len(path_list))
print(len(yield_list))
print(len(opercular_list))
print(len(region_list))
print(len(age_list))
print(len(gender_list))
print(len(manual_exclude_lists))

Loaded 22 NWB files
28
28
28
28
28
28
28
28
28

In [11]:
import fnmatch
import re
import numpy as np
import pandas as pd

def imec_key_sorter(key):
    match = re.search(r"imec(\d+)", key)
    return int(match.group(1)) if match else float("inf")

def get_imec_keys(data, nwb_path):
    """Match insertion-selection logic from the neural analysis loop."""
    keys = list(data.keys())
    keys = [k for k in keys if fnmatch.fnmatch(k, "*imec*")]
    ks_keys = [k for k in keys if "KS4" in k]
    if ks_keys:
        keys = ks_keys
    th8_keys = [k for k in keys if "Th=8" in k]
    if th8_keys:
        keys = th8_keys
    else:
        th_keys = [k for k in keys if "Th=" in k]
        if th_keys:
            keys = th_keys
    keys = [
        k for k in keys
        if not fnmatch.fnmatch(k, "*sentgen*") and not fnmatch.fnmatch(k, "*_auto*")
    ]
    if "NP137" in str(nwb_path) or "NP139_B2" in str(nwb_path):
        keys = [k for k in keys if "imec1" not in k]
    return sorted(keys, key=imec_key_sorter)

# Collect behavioral trial info (start, end, duration) across all NWB files.
prod_trials = []
sens_trials = []
insertion = 0

for i in range(len(nwb_paths)):
    data = nap.load_file(nwb_paths[i])
    patient_id = nwb_paths[i].stem
    imec_keys = get_imec_keys(data, nwb_paths[i])
    insertion_ids = list(range(insertion, insertion + len(imec_keys)))
    insertion += len(imec_keys)
    print(f"{patient_id}  insertions {insertion_ids}  ({', '.join(imec_keys)})")

    def _append_trials(trial_list, onsets, offsets, trial_type):
        for s_t, e_t in zip(onsets, offsets):
            trial_list.append({
                "patient_id": patient_id,
                "nwb_index": i,
                "insertion_id": insertion_ids[0] if insertion_ids else None,
                "insertion_ids": insertion_ids,
                "trial_type": trial_type,
                "start": float(s_t),
                "end": float(e_t),
                "duration": float(e_t) - float(s_t),
            })

    if "ProdSpeechWords" in data:
        speech_prod_times = data["ProdSpeechWords"]
        prod_onsets = np.asarray(speech_prod_times.start, dtype=float).ravel()
        prod_offsets = np.asarray(speech_prod_times.end, dtype=float).ravel()
        _append_trials(prod_trials, prod_onsets, prod_offsets, "speech_production")
        print(f"  prod: {len(prod_onsets)} trials  (insertion_ids={insertion_ids})")
    else:
        print("  prod: no ProdSpeechWords, skipping")

    if ("StimSpeechWords" in data) or ("mfa_stim_words" in data):
        speech_sens_times = data["StimSpeechWords"] if "StimSpeechWords" in data else data["mfa_stim_words"]
        sens_onsets = np.asarray(speech_sens_times.start, dtype=float).ravel()
        sens_offsets = np.asarray(speech_sens_times.end, dtype=float).ravel()
        _append_trials(sens_trials, sens_onsets, sens_offsets, "speech_reception")
        print(f"  sens: {len(sens_onsets)} trials  (insertion_ids={insertion_ids})")
    else:
        print("  sens: no StimSpeechWords/mfa_stim_words, skipping")

prod_trials = pd.DataFrame(prod_trials)
sens_trials = pd.DataFrame(sens_trials)
print(f"\nTotal prod trial rows: {len(prod_trials)}")
print(f"Total sens trial rows: {len(sens_trials)}")

NP93_B1  insertions [0]  (NP93_B1_g0_imec0_withoutKSmc)
  prod: 114 trials  (insertion_ids=[0])
  sens: 1418 trials  (insertion_ids=[0])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP95_B1  insertions [1]  (NP95_B1_g0_imec1)
  prod: 263 trials  (insertion_ids=[1])
  sens: 623 trials  (insertion_ids=[1])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP101_B3  insertions [2]  (NP101_B3_g0_imec0)
  prod: no ProdSpeechWords, skipping
  sens: 1057 trials  (insertion_ids=[2])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP105_B1  insertions [3]  (NP105_B1_g0_imec0)
  prod: 263 trials  (insertion_ids=[3])
  sens: 573 trials  (insertion_ids=[3])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP113_B1  insertions [4, 5, 6]  (NP113_B1_g0_imec0_KS4_Th=8, NP113_B1_g0_imec1_KS4_Th=8, NP113_B1_g0_imec2_KS4_Th=8)
  prod: 725 trials  (insertion_ids=[4, 5, 6])
  sens: 100 trials  (insertion_ids=[4, 5, 6])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP114_B1  insertions [7]  (NP114_B1_g0_imec0)
  prod: 112 trials  (insertion_ids=[7])
  sens: 496 trials  (insertion_ids=[7])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP116_B2  insertions [8]  (NP116_B2_g0_imec0)
  prod: 127 trials  (insertion_ids=[8])
  sens: 389 trials  (insertion_ids=[8])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP122_B1  insertions [9]  (NP122_B1_g0_imec0)
  prod: 813 trials  (insertion_ids=[9])
  sens: 461 trials  (insertion_ids=[9])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP128_B1  insertions [10, 11]  (NP128_B1_g0_imec0_KS4_Th=12, NP128_B1_g0_imec1_KS4_Th=12)
  prod: 814 trials  (insertion_ids=[10, 11])
  sens: 1023 trials  (insertion_ids=[10, 11])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP129_B1  insertions [12]  (NP129_B1_g0_imec0)
  prod: 166 trials  (insertion_ids=[12])
  sens: 1023 trials  (insertion_ids=[12])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP132_B2  insertions [13]  (NP132_B2_g0_imec0_KS4_Th=8)
  prod: 429 trials  (insertion_ids=[13])
  sens: no StimSpeechWords/mfa_stim_words, skipping

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP132_B3  insertions [14]  (NP132_B3_g0_imec0_KS4_Th=8)
  prod: 265 trials  (insertion_ids=[14])
  sens: no StimSpeechWords/mfa_stim_words, skipping

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP136_B1  insertions [15]  (NP136_B1_g0_imec0_KS4)
  prod: 129 trials  (insertion_ids=[15])
  sens: 100 trials  (insertion_ids=[15])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP137_B1  insertions [16]  (NP137_B1_g0_imec0_KS4)
  prod: 126 trials  (insertion_ids=[16])
  sens: 729 trials  (insertion_ids=[16])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP138_B1  insertions [17, 18]  (NP138_B1_g0_imec0_KS4, NP138_B1_g0_imec1_KS4)
  prod: 368 trials  (insertion_ids=[17, 18])
  sens: 1023 trials  (insertion_ids=[17, 18])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP139_B1  insertions [19, 20]  (NP139_B1_g0_imec0_KS4, NP139_B1_g0_imec1_KS4)
  prod: 164 trials  (insertion_ids=[19, 20])
  sens: 1023 trials  (insertion_ids=[19, 20])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP139_B2  insertions [21]  (NP139_B2_g0_imec0_KS4)
  prod: 383 trials  (insertion_ids=[21])
  sens: no StimSpeechWords/mfa_stim_words, skipping

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP147_B2  insertions [22]  (NP147_B2_g0_imec0_KS4_Th=7)
  prod: 470 trials  (insertion_ids=[22])
  sens: 100 trials  (insertion_ids=[22])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP150_B1  insertions [23, 24]  (NP150_B1_g0_imec0_KS4_Th=12, NP150_B1_g0_imec1_KS4_Th=12)
  prod: 216 trials  (insertion_ids=[23, 24])
  sens: 1023 trials  (insertion_ids=[23, 24])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)
/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP153_B1  insertions [25]  (catgt_NP153_B1_g0_imec0_KS4_Th=8)
  prod: 599 trials  (insertion_ids=[25])
  sens: 24 trials  (insertion_ids=[25])

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

NP171_B1  insertions [26]  (catgt_NP171_B1_g0_imec0_KS4_Th=8)
  prod: no ProdSpeechWords, skipping
  sens: no StimSpeechWords/mfa_stim_words, skipping
NP174_B3  insertions [27]  (catgt_NP174_B3_g0_imec0_KS4_Th=8)
  prod: 514 trials  (insertion_ids=[27])
  sens: no StimSpeechWords/mfa_stim_words, skipping

Total prod trial rows: 7060
Total sens trial rows: 11185

/userdata/gumbach/miniforge3/envs/my_se2nwb/lib/python3.10/site-packages/pynapple/io/interface_nwb.py:133: UserWarning: Some starts and ends are equal. Removing 1 microsecond!
  data = nap.IntervalSet(df)

In [12]:
def patient_duration_summary(trials_df, label):
    """One row per patient: trial count, duration range, median (seconds)."""
    if trials_df.empty:
        return pd.DataFrame(columns=["patient_id", "n_trials", "duration_min", "duration_max", "duration_median"])

    per_patient = (
        trials_df.groupby("patient_id", as_index=False)
        .agg(
            insertion_id=("insertion_id", "first"),
            insertion_ids=("insertion_ids", "first"),
            n_trials=("duration", "count"),
            duration_min=("duration", "min"),
            duration_max=("duration", "max"),
            duration_median=("duration", "median"),
        )
        .set_index("patient_id")
    )
    per_patient.index.name = label
    return per_patient

def trial_counts_per_insertion(trials_df, n_insertions):
    """Trial count per insertion; insertions with no events count as 0."""
    counts = pd.Series(0, index=range(n_insertions), dtype=int)
    if trials_df.empty:
        return counts
    per_insertion = (
        trials_df.drop(columns=["insertion_id"])
        .explode("insertion_ids")
        .rename(columns={"insertion_ids": "insertion_id"})
        .groupby("insertion_id")
        .size()
    )
    counts.loc[per_insertion.index] = per_insertion
    return counts

prod_by_patient = patient_duration_summary(prod_trials, "speech_production")
sens_by_patient = patient_duration_summary(sens_trials, "speech_reception")

print("=== Speech production (per patient) ===")
display(prod_by_patient)

print("\n=== Speech reception (per patient) ===")
display(sens_by_patient)

n_insertions = len(manual_exclude_lists)
prod_per_insertion = trial_counts_per_insertion(prod_trials, n_insertions)
sens_per_insertion = trial_counts_per_insertion(sens_trials, n_insertions)

summary = pd.DataFrame({
    "n_events": [
        len(prod_trials),
        len(sens_trials),
    ],
    "mean_duration": [
        prod_trials["duration"].mean() if len(prod_trials) else np.nan,
        sens_trials["duration"].mean() if len(sens_trials) else np.nan,
    ],
    "std_duration": [
        prod_trials["duration"].std() if len(prod_trials) else np.nan,
        sens_trials["duration"].std() if len(sens_trials) else np.nan,
    ],
    "n_trials_min_across_insertions": [
        prod_per_insertion.min(),
        sens_per_insertion.min(),
    ],
    "n_trials_max_across_insertions": [
        prod_per_insertion.max(),
        sens_per_insertion.max(),
    ],
    "n_trials_median_across_insertions": [
        prod_per_insertion.median(),
        sens_per_insertion.median(),
    ],
}, index=["speech_production", "speech_reception"])

print("\n=== Summary ===")
display(summary)

=== Speech production (per patient) ===

,insertion_id,insertion_ids,n_trials,duration_min,duration_max,duration_median
speech_production,,,,,,
NP105_B1,3,[3],263,0.049999,1.045399,0.427782
NP113_B1,4,"[4, 5, 6]",725,0.030000,1.490000,0.570151
NP114_B1,7,[7],112,0.079999,1.480000,0.940000
NP116_B2,8,[8],127,0.039999,1.060000,0.520000
NP122_B1,9,[9],813,0.069999,1.580000,0.370000
NP128_B1,10,"[10, 11]",814,0.029999,1.520000,0.310000
NP129_B1,12,[12],166,0.030000,2.560000,0.460000
NP132_B2,13,[13],429,0.049999,1.029999,0.395400
NP132_B3,14,[14],265,0.029999,1.059999,0.437459
NP136_B1,15,[15],129,0.109999,1.670000,0.800000
NP137_B1,16,[16],126,0.220000,1.300000,0.545000
NP138_B1,17,"[17, 18]",368,0.059999,1.210000,0.349999
NP139_B1,19,"[19, 20]",164,0.069999,0.860000,0.522950
NP139_B2,21,[21],383,0.059999,0.740000,0.279999
NP147_B2,22,[22],470,0.059999,1.530000,0.489999
NP150_B1,23,"[23, 24]",216,0.079999,1.260000,0.500000
NP153_B1,25,[25],599,0.059999,1.770000,0.640000
NP174_B3,27,[27],514,0.029999,2.055953,0.420000
NP93_B1,0,[0],114,0.119999,1.170000,0.600000
NP95_B1,1,[1],263,0.049999,1.349999,0.480000

=== Speech reception (per patient) ===

,insertion_id,insertion_ids,n_trials,duration_min,duration_max,duration_median
speech_reception,,,,,,
NP101_B3,2,[2],1057,0.049999,0.940000,0.239999
NP105_B1,3,[3],573,0.069999,0.810000,0.390000
NP113_B1,4,"[4, 5, 6]",100,0.629410,0.875415,0.750511
NP114_B1,7,[7],496,0.029999,0.915860,0.279999
NP116_B2,8,[8],389,0.069999,0.820000,0.390000
NP122_B1,9,[9],461,0.069999,0.915860,0.440000
NP128_B1,10,"[10, 11]",1023,0.039999,0.778500,0.229999
NP129_B1,12,[12],1023,0.039999,0.748594,0.229999
NP136_B1,15,[15],100,0.600000,0.905287,0.766100
NP137_B1,16,[16],729,0.049999,0.738300,0.219999
NP138_B1,17,"[17, 18]",1023,0.039999,0.775700,0.229999
NP139_B1,19,"[19, 20]",1023,0.039999,0.775683,0.229999
NP147_B2,22,[22],100,0.629410,0.875415,0.750511
NP150_B1,23,"[23, 24]",1023,0.039999,0.775700,0.229999
NP153_B1,25,[25],24,0.629410,0.835146,0.742935
NP93_B1,0,[0],1418,0.039999,0.930000,0.249999
NP95_B1,1,[1],623,0.069999,0.856000,0.390000

=== Summary ===

,n_events,mean_duration,std_duration,n_trials_min_across_insertions,n_trials_max_across_insertions,n_trials_median_across_insertions
speech_production,7060,0.476526,0.272956,0,814,264.0
speech_reception,11185,0.317060,0.194069,0,1418,534.5